productionData = [
    {
        "name": "Miami-Dade County",
        "biomass production": "84.4",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "1285.6",
        "nuclear production": "1658",
        "chp production": "0",
        "petroleum production": "0.1",
        "solar production": "76.8",
        "wind production": "0"
    },
    {
        "name": "Broward County",
        "biomass production": "64.9",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "2460.6",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "1.4",
        "wind production": "0"
    },
    {
        "name": "Palm Beach County",
        "biomass production": "239.9",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "5103.5",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "36",
        "solar production": "74.5",
        "wind production": "0"
    },
    {
        "name": "Hillsborough County",
        "biomass production": "62.5",
        "coal production": "1602",
        "hydroelectric production": "0",
        "natural gas production": "1910",
        "nuclear production": "0",
        "chp production": "68",
        "petroleum production": "0",
        "solar production": "379.4",
        "wind production": "0"
    },
    {
        "name": "Orange County",
        "biomass production": "3.2",
        "coal production": "894",
        "hydroelectric production": "0",
        "natural gas production": "1128",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "70.9",
        "wind production": "0"
    },
    {
        "name": "Pinellas County",
        "biomass production": "58.1",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "1255",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "253",
        "solar production": "1.9",
        "wind production": "0"
    },
    {
        "name": "Duval County",
        "biomass production": "9",
        "coal production": "586",
        "hydroelectric production": "0",
        "natural gas production": "2018.4",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "212",
        "solar production": "35.2",
        "wind production": "0"
    },
    {
        "name": "Lee County",
        "biomass production": "55",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "2638",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "108",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Polk County",
        "biomass production": "0",
        "coal production": "503",
        "hydroelectric production": "0",
        "natural gas production": "4724.5",
        "nuclear production": "0",
        "chp production": "229",
        "petroleum production": "114",
        "solar production": "232.8",
        "wind production": "0"
    },
    {
        "name": "Brevard County",
        "biomass production": "9.6",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "2972.2",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "84.9",
        "wind production": "0"
    },
    {
        "name": "Pasco County",
        "biomass production": "26",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "1476.2",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Volusia County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "2589",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "366",
        "solar production": "75.3",
        "wind production": "0"
    },
    {
        "name": "Seminole County",
        "biomass production": "4.8",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "11.5",
        "wind production": "0"
    },
    {
        "name": "Sarasota County",
        "biomass production": "6.4",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Manatee County",
        "biomass production": "1.6",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "1254.5",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "1618",
        "solar production": "149.4",
        "wind production": "0"
    },
    {
        "name": "Collier County",
        "biomass production": "4",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Osceola County",
        "biomass production": "8.4",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "1684",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "417",
        "solar production": "3.8",
        "wind production": "0"
    },
    {
        "name": "Lake County",
        "biomass production": "12.5",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "4.3",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Marion County",
        "biomass production": "3.8",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "St. Lucie County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "318",
        "nuclear production": "1968",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "149.4",
        "wind production": "0"
    },
    {
        "name": "Escambia County",
        "biomass production": "79",
        "coal production": "924",
        "hydroelectric production": "0",
        "natural gas production": "11.7",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "50",
        "wind production": "0"
    },
    {
        "name": "Leon County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "503.1",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "20",
        "wind production": "0"
    },
    {
        "name": "St. Johns County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Alachua County",
        "biomass production": "102.5",
        "coal production": "232",
        "hydroelectric production": "0",
        "natural gas production": "351.2",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "2.8",
        "wind production": "0"
    },
    {
        "name": "Clay County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Okaloosa County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "30",
        "wind production": "0"
    },
    {
        "name": "Hernando County",
        "biomass production": "1.6",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Charlotte County",
        "biomass production": "2.8",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "159.4",
        "wind production": "0"
    },
    {
        "name": "Santa Rosa County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "247.9",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "40",
        "wind production": "0"
    },
    {
        "name": "Indian River County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "149.8",
        "wind production": "0"
    },
    {
        "name": "Martin County",
        "biomass production": "0",
        "coal production": "330",
        "hydroelectric production": "0",
        "natural gas production": "2209",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "74.5",
        "wind production": "0"
    },
    {
        "name": "Citrus County",
        "biomass production": "0",
        "coal production": "1422",
        "hydroelectric production": "0",
        "natural gas production": "1610",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Bay County",
        "biomass production": "45.8",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "511",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "32",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Sumter County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Flagler County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Highlands County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "24",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "24",
        "solar production": "45",
        "wind production": "0"
    },
    {
        "name": "Nassau County",
        "biomass production": "122",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "21.3",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Walton County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Putnam County",
        "biomass production": "69.7",
        "coal production": "1309",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "224.3",
        "wind production": "0"
    },
    {
        "name": "Columbia County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "149.4",
        "wind production": "0"
    },
    {
        "name": "Monroe County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Gadsden County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "43.5",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Suwannee County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "99",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "50",
        "solar production": "83.3",
        "wind production": "0"
    },
    {
        "name": "Hendry County",
        "biomass production": "44.6",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "149.4",
        "wind production": "0"
    },
    {
        "name": "Okeechobee County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "1723.1",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "74.5",
        "wind production": "0"
    },
    {
        "name": "Jackson County",
        "biomass production": "4.8",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Levy County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "DeSoto County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "253.3",
        "wind production": "0"
    },
    {
        "name": "Wakulla County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "226",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "42",
        "wind production": "0"
    },
    {
        "name": "Baker County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "74.5",
        "wind production": "0"
    },
    {
        "name": "Bradford County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Washington County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Hardee County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "1847",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Taylor County",
        "biomass production": "43.5",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "5.1",
        "wind production": "0"
    },
    {
        "name": "Holmes County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Gilchrist County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "74.9",
        "wind production": "0"
    },
    {
        "name": "Madison County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Dixie County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Union County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Hamilton County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "15.9",
        "petroleum production": "0",
        "solar production": "74.9",
        "wind production": "0"
    },
    {
        "name": "Jefferson County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Glades County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Calhoun County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Franklin County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Gulf County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Liberty County",
        "biomass production": "13.7",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    },
    {
        "name": "Lafayette County",
        "biomass production": "0",
        "coal production": "0",
        "hydroelectric production": "0",
        "natural gas production": "0",
        "nuclear production": "0",
        "chp production": "0",
        "petroleum production": "0",
        "solar production": "0",
        "wind production": "0"
    }
  ]
